doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true        
        dql:
            string_functions:
                IFNULL: App\DQL\IfNull
                DAY:  App\DQL\Day
                MONTH: App\DQL\Month
                YEAR: App\DQL\Year
                GROUP_CONCAT: App\DQL\GroupConcat
                DATE: App\DQL\Date
                REPLACE: App\DQL\Replace
                LPAD: App\DQL\Lpad
                IF: App\DQL\IfElse
            datetime_functions:
                DATE_FORMAT: App\DateFormat
