security:

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_ALL]

        ROLE_ALL: [ROLE_ADMIN, ROLE_GRUPO_ALL, ROLE_USUARIO_ALL, ROLE_MODULO_ALL, ROLE_CONFIGURACION_ALL]

        ROLE_PROBLEMA: [ROLE_USER, ROLE_PROBLEMA, ROLE_MENU_PEDIDO, ROLE_MESADA_CRUD, ROLE_MENU_PEDIDO, ROLE_PEDIDO, ROLE_BANDEJA_CRUD, ROLE_SOLUCION_CRUD, ROLE_REVISION_CRUD, ROLE_MENU_CONFIGURACION]

        #PLANIFICAR
        ROLE_PLANIFICAR: [ROLE_USER, ROLE_PLANIFICAR]

        #SIEMBRA
        ROLE_SIEMBRA: [ROLE_USER, ROLE_SIEMBRA]

        #CAMARA
        ROLE_ENTRADA_CAMARA: [ROLE_USER, ROLE_ENTRADA_CAMARA]
        ROLE_SALIDA_CAMARA: [ROLE_USER, ROLE_SALIDA_CAMARA]

        ROLE_PAGO: [ROLE_USER, ROLE_PAGO]
        ROLE_CLIENTE: [ROLE_USER, ROLE_CLIENTE]
        ROLE_MODULO_ALL: [ROLE_RESERVA, ROLE_PEDIDO, ROLE_SITUACION_CLIENTE, ROLE_PAGO, ROLE_REMITO, ROLE_ENTREGA, ROLE_AGENDA, ROLE_ENTREGA, ROLE_PROBLEMA, ROLE_STOCK, ROLE_SIEMBRA, ROLE_PLANIFICAR, ROLE_STOCK, ROLE_CAJA, ROLE_ENTRADA_CAMARA, ROLE_SALIDA_CAMARA, ROLE_ESTADISTICAS, ROLE_ORDEN_CARGA, ROLE_GASTO, ROLE_FACTURA, ROLE_PROVEEDOR, ROLE_DEVOLUCION]

        #TIPO USUARIO
        ROLE_TIPO_USUARIO: [ROLE_USER, ROLE_TIPO_USUARIO]


        #---------------------------------------- PEDIDOS   ----------------------------------------#

        #MENU PEDIDOS
        ROLE_MENU_PEDIDO: [ ROLE_USER, ROLE_MENU_PEDIDO ]

        # PEDIDO
        ROLE_PEDIDO: [ ROLE_USER, ROLE_PEDIDO, ROLE_MENU_PEDIDO ]
        ROLE_PEDIDO_VIEW: [ ROLE_MENU_PEDIDO, ROLE_PEDIDO_VIEW ]
        ROLE_PEDIDO_CREATE: [ ROLE_PEDIDO_VIEW, ROLE_PEDIDO_CREATE ]
        ROLE_PEDIDO_EDIT: [ ROLE_PEDIDO_VIEW, ROLE_PEDIDO_EDIT ]
        ROLE_PEDIDO_DELETE: [ ROLE_PEDIDO_VIEW, ROLE_PEDIDO_DELETE ]
        ROLE_PEDIDO_CRUD: [ ROLE_PEDIDO_CREATE, ROLE_PEDIDO_EDIT, ROLE_PEDIDO_DELETE, ROLE_PEDIDO_CRUD ]

        # RESERVA
        ROLE_RESERVA: [ ROLE_USER, ROLE_RESERVA, ROLE_MENU_PEDIDO ]
        ROLE_RESERVA_VIEW: [ ROLE_MENU_PEDIDO, ROLE_RESERVA_VIEW ]
        ROLE_RESERVA_CREATE: [ ROLE_RESERVA_VIEW, ROLE_RESERVA_CREATE ]
        ROLE_RESERVA_EDIT: [ ROLE_RESERVA_VIEW, ROLE_RESERVA_EDIT ]
        ROLE_RESERVA_DELETE: [ ROLE_RESERVA_VIEW, ROLE_PEDIDO_DELETE ]
        ROLE_RESERVA_CRUD: [ ROLE_RESERVA_CREATE, ROLE_RESERVA_EDIT, ROLE_RESERVA_DELETE, ROLE_RESERVA_CRUD ]

        # DEVOLUCION
        ROLE_DEVOLUCION: [ ROLE_USER, ROLE_DEVOLUCION, ROLE_MENU_PEDIDO ]
        ROLE_DEVOLUCION_VIEW: [ ROLE_MENU_PEDIDO, ROLE_DEVOLUCION_VIEW ]
        ROLE_DEVOLUCION_CREATE: [ ROLE_DEVOLUCION_VIEW, ROLE_DEVOLUCION_CREATE ]
        ROLE_DEVOLUCION_EDIT: [ ROLE_DEVOLUCION_VIEW, ROLE_DEVOLUCION_EDIT ]
        ROLE_DEVOLUCION_DELETE: [ ROLE_DEVOLUCION_VIEW, ROLE_PEDIDO_DELETE ]
        ROLE_DEVOLUCION_CRUD: [ ROLE_DEVOLUCION_CREATE, ROLE_DEVOLUCION_EDIT, ROLE_DEVOLUCION_DELETE, ROLE_DEVOLUCION_CRUD ]

        # ENTREGA
        ROLE_ENTREGA: [ ROLE_USER, ROLE_ENTREGA, ROLE_MENU_PEDIDO ]
        ROLE_ENTREGA_VIEW: [ ROLE_MENU_PEDIDO, ROLE_ENTREGA_VIEW ]
        ROLE_ENTREGA_CREATE: [ ROLE_ENTREGA_VIEW, ROLE_RENTREGA_CREATE ]
        ROLE_ENTREGA_EDIT: [ ROLE_ENTREGA_VIEW, ROLE_RENTREGA_EDIT ]
        ROLE_ENTREGA_DELETE: [ ROLE_ENTREGA_VIEW, ROLE_PEDIDO_DELETE ]
        ROLE_ENTREGA_CRUD: [ ROLE_ENTREGA_CREATE, ROLE_ENTREGA_EDIT, ROLE_ENTREGA_DELETE, ROLE_ENTREGA_CRUD ]

        # REMITO
        ROLE_REMITO: [ ROLE_USER, ROLE_REMITO, ROLE_MENU_PEDIDO ]
        ROLE_REMITO_VIEW: [ ROLE_MENU_PEDIDO, ROLE_REMITO_VIEW ]
        ROLE_REMITO_CREATE: [ ROLE_REMITO_VIEW, ROLE_REMITO_CREATE ]
        ROLE_REMITO_EDIT: [ ROLE_REMITO_VIEW, ROLE_REMITO_EDIT ]
        ROLE_REMITO_DELETE: [ ROLE_REMITO_VIEW, ROLE_PEDIDO_DELETE ]
        ROLE_REMITO_CRUD: [ ROLE_REMITO_CREATE, ROLE_REMITO_EDIT, ROLE_REMITO_DELETE, ROLE_REMITO_CRUD ]

        #ORDEN CARGA
        ROLE_ORDEN_CARGA: [ ROLE_USER, ROLE_ORDEN_CARGA ]

        #SITUACION CLIENTE
        ROLE_SITUACION_CLIENTE: [ ROLE_USER, ROLE_SITUACION_CLIENTE, ROLE_MENU_PEDIDO ]

        #CAJA
        ROLE_CAJA: [ ROLE_USER, ROLE_CAJA, ROLE_MENU_PEDIDO ]

        #SOTCK
        ROLE_STOCK: [ ROLE_USER, ROLE_STOCK, ROLE_MENU_PEDIDO ]

        #---------------------------------------- CONFIGURACION   ----------------------------------------#

        # AUDITORIA
        ROLE_AUDITORIA_VIEW: [ROLE_MENU_SEGURIDAD, ROLE_AUDITORIA_VIEW]

        # MENU CONFIGURACION
        ROLE_MENU_CONFIGURACION: [ ROLE_USER, ROLE_MENU_CONFIGURACION ]

        # ROLE CONFINGURACION ALL
        ROLE_CONFIGURACION_ALL: [ ROLE_MENU_CONFIGURACION, ROLE_BANDEJA_CRUD, ROLE_MESADA_CRUD, ROLE_ORIGEN_SEMILLA_CRUD, ROLE_VARIEDAD_CRUD, ROLE_SUB_PRODUCTO_CRUD, ROLE_PRODUCTO_CRUD, ROLE_CONFIGURACION_ALL ]

        # USUARIOS
        ROLE_USUARIO_VIEW: [ROLE_MENU_SEGURIDAD, ROLE_USUARIO_VIEW, ROLE_MENU_CONFIGURACION]
        ROLE_USUARIO_CREATE: [ROLE_USUARIO_VIEW, ROLE_USUARIO_CREATE]
        ROLE_USUARIO_EDIT: [ROLE_USUARIO_VIEW, ROLE_USUARIO_EDIT]
        ROLE_USUARIO_DELETE: [ROLE_USUARIO_VIEW, ROLE_USUARIO_DELETE]
        ROLE_USUARIO_CRUD: [ROLE_USUARIO_CREATE, ROLE_USUARIO_EDIT, ROLE_USUARIO_DELETE, ROLE_USUARIO_CRUD]
        ROLE_USUARIO_HABILITAR : [ROLE_USUARIO_VIEW, ROLE_USUARIO_HABILITAR]
        ROLE_USUARIO_DESHABILITAR: [ROLE_USUARIO_VIEW, ROLE_USUARIO_DESHABILITAR]
        ROLE_USUARIO_ALL: [ROLE_USUARIO_CRUD, ROLE_USUARIO_DESHABILITAR, ROLE_USUARIO_HABILITAR, ROLE_USUARIO_ALL, ROLE_MENU_ADMINISTRACION, ROLE_MENU_CONTABLE]

        # BANDEJA
        ROLE_BANDEJA_VIEW: [ROLE_MENU_CONFIGURACION, ROLE_BANDEJA_VIEW]
        ROLE_BANDEJA_CREATE: [ROLE_BANDEJA_VIEW, ROLE_BANDEJA_CREATE]
        ROLE_BANDEJA_EDIT: [ROLE_BANDEJA_VIEW, ROLE_BANDEJA_EDIT]
        ROLE_BANDEJA_DELETE: [ROLE_BANDEJA_VIEW, ROLE_BANDEJA_DELETE]
        ROLE_BANDEJA_CRUD: [ROLE_BANDEJA_CREATE, ROLE_BANDEJA_EDIT, ROLE_BANDEJA_DELETE, ROLE_BANDEJA_CRUD]

        # MESADA
        ROLE_MESADA_VIEW: [ ROLE_MENU_CONFIGURACION, ROLE_MESADA_VIEW ]
        ROLE_MESADA_CREATE: [ ROLE_MESADA_VIEW, ROLE_MESADA_CREATE ]
        ROLE_MESADA_EDIT: [ ROLE_MESADA_VIEW, ROLE_MESADA_EDIT ]
        ROLE_MESADA_DELETE: [ ROLE_MESADA_VIEW, ROLE_MESADA_DELETE ]
        ROLE_MESADA_CRUD: [ ROLE_MESADA_CREATE, ROLE_MESADA_EDIT, ROLE_MESADA_DELETE, ROLE_MESADA_CRUD ]

        # ORIGEN SEMILLA
        ROLE_ORIGEN_SEMILLA_VIEW: [ ROLE_MENU_CONFIGURACION, ROLE_ORIGEN_SEMILLA_VIEW ]
        ROLE_ORIGEN_SEMILLA_CREATE: [ ROLE_ORIGEN_SEMILLA_VIEW, ROLE_ORIGEN_SEMILLA_CREATE ]
        ROLE_ORIGEN_SEMILLA_EDIT: [ ROLE_ORIGEN_SEMILLA_VIEW, ROLE_ORIGEN_SEMILLA_EDIT ]
        ROLE_ORIGEN_SEMILLA_DELETE: [ ROLE_ORIGEN_SEMILLA_VIEW, ROLE_ORIGEN_SEMILLA_DELETE ]
        ROLE_ORIGEN_SEMILLA_CRUD: [ ROLE_ORIGEN_SEMILLA_CREATE, ROLE_ORIGEN_SEMILLA_EDIT, ROLE_ORIGEN_SEMILLA_DELETE, ROLE_ORIGEN_SEMILLA_CRUD ]

        # VARIEDAD
        ROLE_VARIEDAD_VIEW: [ ROLE_MENU_CONFIGURACION, ROLE_VARIEDAD_VIEW ]
        ROLE_VARIEDAD_CREATE: [ ROLE_VARIEDAD_VIEW, ROLE_VARIEDAD_CREATE ]
        ROLE_VARIEDAD_EDIT: [ ROLE_VARIEDAD_VIEW, ROLE_VARIEDAD_EDIT ]
        ROLE_VARIEDAD_DELETE: [ ROLE_VARIEDAD_VIEW, ROLE_VARIEDAD_DELETE ]
        ROLE_VARIEDAD_CRUD: [ ROLE_VARIEDAD_CREATE, ROLE_VARIEDAD_EDIT, ROLE_VARIEDAD_DELETE, ROLE_VARIEDAD_CRUD ]

        # SUB PRODUCTO
        ROLE_SUB_PRODUCTO_VIEW: [ ROLE_MENU_CONFIGURACION, ROLE_SUB_PRODUCTO_VIEW ]
        ROLE_SUB_PRODUCTO_CREATE: [ ROLE_SUB_PRODUCTO_VIEW, ROLE_SUB_PRODUCTO_CREATE ]
        ROLE_SUB_PRODUCTO_EDIT: [ ROLE_SUB_PRODUCTO_VIEW, ROLE_SUB_PRODUCTO_EDIT ]
        ROLE_SUB_PRODUCTO_DELETE: [ ROLE_SUB_PRODUCTO_VIEW, ROLE_SUB_PRODUCTO_DELETE ]
        ROLE_SUB_PRODUCTO_CRUD: [ ROLE_SUB_PRODUCTO_CREATE, ROLE_SUB_PRODUCTO_EDIT, ROLE_SUB_PRODUCTO_DELETE, ROLE_SUB_PRODUCTO_CRUD ]

        # PRODUCTO
        ROLE_PRODUCTO_VIEW: [ ROLE_MENU_CONFIGURACION, ROLE_PRODUCTO_VIEW ]
        ROLE_PRODUCTO_CREATE: [ ROLE_PRODUCTO_VIEW, ROLE_PRODUCTO_CREATE ]
        ROLE_PRODUCTO_EDIT: [ ROLE_PRODUCTO_VIEW, ROLE_PRODUCTO_EDIT ]
        ROLE_PRODUCTO_DELETE: [ ROLE_PRODUCTO_VIEW, ROLE_PRODUCTO_DELETE ]
        ROLE_PRODUCTO_CRUD: [ ROLE_PRODUCTO_CREATE, ROLE_PRODUCTO_EDIT, ROLE_PRODUCTO_DELETE, ROLE_PRODUCTO_CRUD ]

        # REVISION
        ROLE_REVISION_VIEW: [ ROLE_MENU_CONFIGURACION, ROLE_REVISION_VIEW ]
        ROLE_REVISION_CREATE: [ ROLE_REVISION_VIEW, ROLE_REVISION_CREATE ]
        ROLE_REVISION_EDIT: [ ROLE_REVISION_VIEW, ROLE_REVISION_EDIT ]
        ROLE_REVISION_DELETE: [ ROLE_REVISION_VIEW, ROLE_REVISION_DELETE ]
        ROLE_REVISION_CRUD: [ ROLE_REVISION_CREATE, ROLE_REVISION_EDIT, ROLE_REVISION_DELETE, ROLE_REVISION_CRUD ]

        # SOLUCION
        ROLE_SOLUCION_VIEW: [ ROLE_MENU_CONFIGURACION, ROLE_SOLUCION_VIEW ]
        ROLE_SOLUCION_CREATE: [ ROLE_SOLUCION_VIEW, ROLE_SOLUCION_CREATE ]
        ROLE_SOLUCION_EDIT: [ ROLE_SOLUCION_VIEW, ROLE_SOLUCION_EDIT ]
        ROLE_SOLUCION_DELETE: [ ROLE_SOLUCION_VIEW, ROLE_SOLUCION_DELETE ]
        ROLE_SOLUCION_CRUD: [ ROLE_SOLUCION_CREATE, ROLE_SOLUCION_EDIT, ROLE_SOLUCION_DELETE, ROLE_SOLUCION_CRUD ]

        # MOTIVO ELIMINACION
        ROLE_MOTIVO_ELIMINACION_VIEW: [ ROLE_MENU_CONFIGURACION, ROLE_MOTIVO_ELIMINACION_VIEW ]
        ROLE_MOTIVO_ELIMINACION_CREATE: [ ROLE_MOTIVO_ELIMINACION_VIEW, ROLE_MOTIVO_ELIMINACION_CREATE ]
        ROLE_MOTIVO_ELIMINACION_EDIT: [ ROLE_MOTIVO_ELIMINACION_VIEW, ROLE_MOTIVO_ELIMINACION_EDIT ]
        ROLE_MOTIVO_ELIMINACION_DELETE: [ ROLE_MOTIVO_ELIMINACION_VIEW, ROLE_MOTIVO_ELIMINACION_DELETE ]
        ROLE_MOTIVO_ELIMINACION_CRUD: [ ROLE_MOTIVO_ELIMINACION_CREATE, ROLE_MOTIVO_ELIMINACION_EDIT, ROLE_MOTIVO_ELIMINACION_DELETE, ROLE_MOTIVO_ELIMINACION_CRUD ]


        #---------------------------------------- ADMINISTRACION   ----------------------------------------#
        #MENU ADMINISTRACION
        ROLE_MENU_ADMINISTRACION: [ ROLE_USER, ROLE_MENU_ADMINISTRACION ]

        #ESTADISTICAS
        ROLE_ESTADISTICAS: [ ROLE_USER, ROLE_ESTADISTICAS ]

        #GRUPOS
        ROLE_MENU_SEGURIDAD: [ ROLE_USER, ROLE_MENU_SEGURIDAD ]
        ROLE_GRUPO_VIEW: [ ROLE_MENU_SEGURIDAD, ROLE_GRUPO_VIEW ]
        ROLE_GRUPO_CREATE: [ ROLE_GRUPO_VIEW, ROLE_GRUPO_CREATE ]
        ROLE_GRUPO_EDIT: [ ROLE_GRUPO_VIEW, ROLE_GRUPO_EDIT ]
        ROLE_GRUPO_DELETE: [ ROLE_GRUPO_VIEW, ROLE_GRUPO_DELETE ]
        ROLE_GRUPO_RESET_PASSWORD: [ ROLE_GRUPO_VIEW, ROLE_GRUPO_RESET_PASSWORD ]
        ROLE_GRUPO_CRUD: [ ROLE_GRUPO_CREATE, ROLE_GRUPO_EDIT, ROLE_GRUPO_DELETE, ROLE_GRUPO_CRUD ]
        ROLE_GRUPO_ALL: [ ROLE_GRUPO_CRUD, ROLE_GRUPO_RESET_PASSWORD, ROLE_GRUPO_ALL ]


        #---------------------------------------- CONTABLE   ----------------------------------------#

        #MENU CONTABLE
        ROLE_MENU_CONTABLE: [ ROLE_USER, ROLE_MENU_CONTABLE ]

        #CONTABLE ALL
        ROLE_CONTABLE_ALL: [ ROLE_MENU_CONTABLE, ROLE_CONTABLE_ALL, ROLE_GASTO, ROLE_FACTURA, ROLE_PROVEEDOR ]

        #GASTO
        ROLE_GASTO: [ ROLE_USER, ROLE_GASTO, ROLE_MENU_CONTABLE ]

        #FACTURA
        ROLE_FACTURA: [ ROLE_USER, ROLE_FACTURA, ROLE_MENU_CONTABLE ]

        #PROVEEDOR
        ROLE_PROVEEDOR: [ ROLE_USER, ROLE_PROVEEDOR, ROLE_MENU_CONTABLE ]