security:
    # Para definir los roles se usa patrón ROLE_MODULO_ACCION
    # MODULO debe ser igual a la url mostrada al acceder al módulo
    # ACCION generalmente va a ser LECTURA o ESCRITURA
    # por ejemplo ROLE_OBRAS_LECTURA
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_ALL]

        ROLE_ALL: [ROLE_ADMIN, ROLE_GRUPO_ALL, ROLE_USUARIO_ALL, ROLE_AUDITORIA_VIEW, ROLE_MODULO_ALL, ROLE_CONFIGURACION_ALL]


        #MENU PEDIDOS
        ROLE_MENU_PEDIDO: [ ROLE_USER, ROLE_MENU_PEDIDO ]
        ROLE_PEDIDO: [ROLE_USER, ROLE_PEDIDO, ROLE_MENU_PEDIDO]
        ROLE_RESERVA: [ROLE_USER, ROLE_RESERVA, ROLE_MENU_PEDIDO]
        ROLE_ENTREGA: [ROLE_USER, ROLE_ENTREGA, ROLE_MENU_PEDIDO]
        ROLE_REMITO: [ROLE_USER, ROLE_REMITO, ROLE_MENU_PEDIDO]
        ROLE_SITUACION_CLIENTE: [ROLE_USER, ROLE_SITUACION_CLIENTE, ROLE_MENU_PEDIDO]
        ROLE_CAJA: [ROLE_USER, ROLE_CAJA, ROLE_MENU_PEDIDO]
        ROLE_STOCK: [ROLE_USER, ROLE_STOCK, ROLE_MENU_PEDIDO]

        #PLANIFICAR
        ROLE_PLANIFICAR: [ROLE_USER, ROLE_PLANIFICAR]

        #SIEMBRA
        ROLE_SIEMBRA: [ROLE_USER, ROLE_SIEMBRA]

        #CAMARA
        ROLE_ENTRADA_CAMARA: [ROLE_USER, ROLE_ENTRADA_CAMARA]
        ROLE_SALIDA_CAMARA: [ROLE_USER, ROLE_SALIDA_CAMARA]

        ROLE_PAGO: [ROLE_USER, ROLE_PAGO]
        ROLE_CLIENTE: [ROLE_USER, ROLE_CLIENTE]
        ROLE_MODULO_ALL: [ROLE_RESERVA, ROLE_PEDIDO, ROLE_SITUACION_CLIENTE, ROLE_PAGO, ROLE_REMITO, ROLE_ENTREGA, ROLE_AGENDA, ROLE_ENTREGA, ROLE_PROBLEMAS, ROLE_STOCK, ROLE_SIEMBRA, ROLE_PLANIFICAR, ROLE_STOCK, ROLE_CAJA, ROLE_ENTRADA_CAMARA, ROLE_SALIDA_CAMARA, ROLE_ESTADISTICAS]

        #MENU SEGURIDAD
        ROLE_MENU_SEGURIDAD: [ROLE_USER, ROLE_MENU_SEGURIDAD]
        ROLE_GRUPO_VIEW: [ROLE_MENU_SEGURIDAD, ROLE_GRUPO_VIEW]
        ROLE_GRUPO_CREATE: [ROLE_GRUPO_VIEW, ROLE_GRUPO_CREATE]
        ROLE_GRUPO_EDIT: [ROLE_GRUPO_VIEW, ROLE_GRUPO_EDIT]
        ROLE_GRUPO_DELETE: [ROLE_GRUPO_VIEW, ROLE_GRUPO_DELETE]
        ROLE_GRUPO_RESET_PASSWORD: [ROLE_GRUPO_VIEW, ROLE_GRUPO_RESET_PASSWORD]
        ROLE_GRUPO_CRUD: [ROLE_GRUPO_CREATE, ROLE_GRUPO_EDIT, ROLE_GRUPO_DELETE, ROLE_GRUPO_CRUD]
        ROLE_GRUPO_ALL: [ROLE_GRUPO_CRUD, ROLE_GRUPO_RESET_PASSWORD, ROLE_GRUPO_ALL]

        #CONFIGURACION USUARIOS
        ROLE_USUARIO_VIEW: [ROLE_MENU_SEGURIDAD, ROLE_USUARIO_VIEW]
        ROLE_USUARIO_CREATE: [ROLE_USUARIO_VIEW, ROLE_USUARIO_CREATE]
        ROLE_USUARIO_EDIT: [ROLE_USUARIO_VIEW, ROLE_USUARIO_EDIT]
        ROLE_USUARIO_DELETE: [ROLE_USUARIO_VIEW, ROLE_USUARIO_DELETE]
        ROLE_USUARIO_CRUD: [ROLE_USUARIO_CREATE, ROLE_USUARIO_EDIT, ROLE_USUARIO_DELETE, ROLE_USUARIO_CRUD]
        ROLE_USUARIO_HABILITAR : [ROLE_USUARIO_VIEW, ROLE_USUARIO_HABILITAR]
        ROLE_USUARIO_DESHABILITAR: [ROLE_USUARIO_VIEW, ROLE_USUARIO_DESHABILITAR]
        ROLE_USUARIO_ALL: [ROLE_USUARIO_CRUD, ROLE_USUARIO_DESHABILITAR, ROLE_USUARIO_HABILITAR, ROLE_USUARIO_ALL]

        ROLE_AUDITORIA_VIEW: [ROLE_MENU_SEGURIDAD, ROLE_AUDITORIA_VIEW]

        # ROLE CONFINGURACION ALL
        ROLE_CONFIGURACION_ALL: [ROLE_MENU_CONFIGURACION, ROLE_BANDEJA_CRUD, ROLE_MESADA_CRUD, ROLE_ORIGEN_SEMILLA_CRUD, ROLE_VARIEDAD_CRUD, ROLE_SUB_PRODUCTO_CRUD, ROLE_PRODUCTO_CRUD, ROLE_TIPO_USUARIO, ROLE_CONFIGURACION_ALL]

        # MENU CONFIGURACION
        ROLE_MENU_CONFIGURACION: [ROLE_USER, ROLE_MENU_CONFIGURACION]

        #TIPO USUARIO
        ROLE_TIPO_USUARIO: [ROLE_USER, ROLE_TIPO_USUARIO]

        # BANDEJA
        ROLE_BANDEJA_VIEW: [ROLE_MENU_CONFIGURACION, ROLE_BANDEJA_VIEW]
        ROLE_BANDEJA_CREATE: [ROLE_BANDEJA_VIEW, ROLE_BANDEJA_CREATE]
        ROLE_BANDEJA_EDIT: [ROLE_BANDEJA_VIEW, ROLE_BANDEJA_EDIT]
        ROLE_BANDEJA_DELETE: [ROLE_BANDEJA_VIEW, ROLE_BANDEJA_DELETE]
        ROLE_BANDEJA_CRUD: [ROLE_BANDEJA_CREATE, ROLE_BANDEJA_EDIT, ROLE_BANDEJA_DELETE, ROLE_BANDEJA_CRUD]

        # MESADA
        ROLE_MESADA_VIEW: [ ROLE_MENU_CONFIGURACION, ROLE_MESADA_VIEW ]
        ROLE_MESADA_CREATE: [ ROLE_MESADA_VIEW, ROLE_MESADA_CREATE ]
        ROLE_MESADA_EDIT: [ ROLE_MESADA_VIEW, ROLE_MESADA_EDIT ]
        ROLE_MESADA_DELETE: [ ROLE_MESADA_VIEW, ROLE_MESADA_DELETE ]
        ROLE_MESADA_CRUD: [ ROLE_MESADA_CREATE, ROLE_MESADA_EDIT, ROLE_MESADA_DELETE, ROLE_MESADA_CRUD ]

        # ORIGEN SEMILLA
        ROLE_ORIGEN_SEMILLA_VIEW: [ ROLE_MENU_CONFIGURACION, ROLE_ORIGEN_SEMILLA_VIEW ]
        ROLE_ORIGEN_SEMILLA_CREATE: [ ROLE_ORIGEN_SEMILLA_VIEW, ROLE_ORIGEN_SEMILLA_CREATE ]
        ROLE_ORIGEN_SEMILLA_EDIT: [ ROLE_ORIGEN_SEMILLA_VIEW, ROLE_ORIGEN_SEMILLA_EDIT ]
        ROLE_ORIGEN_SEMILLA_DELETE: [ ROLE_ORIGEN_SEMILLA_VIEW, ROLE_ORIGEN_SEMILLA_DELETE ]
        ROLE_ORIGEN_SEMILLA_CRUD: [ ROLE_ORIGEN_SEMILLA_CREATE, ROLE_ORIGEN_SEMILLA_EDIT, ROLE_ORIGEN_SEMILLA_DELETE, ROLE_ORIGEN_SEMILLA_CRUD ]

        # VARIEDAD
        ROLE_VARIEDAD_VIEW: [ ROLE_MENU_CONFIGURACION, ROLE_VARIEDAD_VIEW ]
        ROLE_VARIEDAD_CREATE: [ ROLE_VARIEDAD_VIEW, ROLE_VARIEDAD_CREATE ]
        ROLE_VARIEDAD_EDIT: [ ROLE_VARIEDAD_VIEW, ROLE_VARIEDAD_EDIT ]
        ROLE_VARIEDAD_DELETE: [ ROLE_VARIEDAD_VIEW, ROLE_VARIEDAD_DELETE ]
        ROLE_VARIEDAD_CRUD: [ ROLE_VARIEDAD_CREATE, ROLE_VARIEDAD_EDIT, ROLE_VARIEDAD_DELETE, ROLE_VARIEDAD_CRUD ]

        # SUB PRODUCTO
        ROLE_SUB_PRODUCTO_VIEW: [ ROLE_MENU_CONFIGURACION, ROLE_SUB_PRODUCTO_VIEW ]
        ROLE_SUB_PRODUCTO_CREATE: [ ROLE_SUB_PRODUCTO_VIEW, ROLE_SUB_PRODUCTO_CREATE ]
        ROLE_SUB_PRODUCTO_EDIT: [ ROLE_SUB_PRODUCTO_VIEW, ROLE_SUB_PRODUCTO_EDIT ]
        ROLE_SUB_PRODUCTO_DELETE: [ ROLE_SUB_PRODUCTO_VIEW, ROLE_SUB_PRODUCTO_DELETE ]
        ROLE_SUB_PRODUCTO_CRUD: [ ROLE_SUB_PRODUCTO_CREATE, ROLE_SUB_PRODUCTO_EDIT, ROLE_SUB_PRODUCTO_DELETE, ROLE_SUB_PRODUCTO_CRUD ]

        # PRODUCTO
        ROLE_PRODUCTO_VIEW: [ ROLE_MENU_CONFIGURACION, ROLE_PRODUCTO_VIEW ]
        ROLE_PRODUCTO_CREATE: [ ROLE_PRODUCTO_VIEW, ROLE_PRODUCTO_CREATE ]
        ROLE_PRODUCTO_EDIT: [ ROLE_PRODUCTO_VIEW, ROLE_PRODUCTO_EDIT ]
        ROLE_PRODUCTO_DELETE: [ ROLE_PRODUCTO_VIEW, ROLE_PRODUCTO_DELETE ]
        ROLE_PRODUCTO_CRUD: [ ROLE_PRODUCTO_CREATE, ROLE_PRODUCTO_EDIT, ROLE_PRODUCTO_DELETE, ROLE_PRODUCTO_CRUD ]

        # ESTADISTICAS
        ROLE_ESTADISTICAS: [ ROLE_USER, ROLE_ESTADISTICAS ]