services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_{{ NOMBRE_ APP }}
    ports:
      - "CAMBIAME:80"
    volumes:
      - .:/var/www/html
    networks:
      - {{ NOMBRE_APP_ }}net

  mariadb:
    image: mariadb:10.6
    container_name: mariadb_{{ NOMBRE_ APP }}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: {{ NOMBRE_ APP }}
    volumes:
      - mariadb_{{ NOMBRE_APP_ }}_data:/var/lib/mysql
    ports:
      - "CAMBIAME:3306"
    networks:
      - {{ NOMBRE_APP_ }}net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_{{ NOMBRE_ APP }}
    environment:
      PMA_HOST: mariadb_{{ NOMBRE_ APP }}
    ports:
      - "CAMBIAME:80"
    depends_on:
      - mariadb
    networks:
      - {{ NOMBRE_APP_ }}net

volumes:
  mariadb_{{ NOMBRE_APP_ }}_data:

networks:
  {{ NOMBRE_APP_ }}net:
    driver: bridge
