services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: babyplant_app
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
    networks:
      database: {}

networks:
  database:
    external: true
