services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_babyplant
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - cliente_net

  mysql:
    image: mysql:8.0
    container_name: mysql_babyplant
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: babyplant
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"  # Puerto expuesto solo si lo necesitas
    networks:
      - cliente_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_babyplant
    environment:
      PMA_HOST: mysql_babyplant
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - cliente_net

volumes:
  mysql_data:

networks:
  cliente_net:
    driver: bridge
